'use strict';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
let sections=[],assemblyActive=false,currentResult=null,currentJob=null,imageURL=null,dirty=true,previewTimer;
const number=id=>{const n=Number($(id).value);if($(id).value.trim()===''||!Number.isFinite(n))throw Error(`${$(id).closest('label')?.textContent.trim()||id}: 数値を入力してください`);return n;};
function failure(error){$('error').hidden=false;$('error').textContent=`入力・操作を確認してください\n${error.message}`;}
async function api(action,data={},binary=false){const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-NG-Token':token},body:JSON.stringify({action,...data})});if(!r.ok){const e=await r.json();throw Error(e.error);}return binary?r.blob():r.json();}
function bind(id,fn){$(id).addEventListener('click',async()=>{try{$('error').hidden=true;await fn();}catch(e){failure(e);}});}
function markDirty(){dirty=true;$('dirty').textContent='変更あり — 計算前に入力を確認';$('preview-note').textContent='編集後の形状は未確認です。';}
function download(name,data,type='application/json'){const blob=data instanceof Blob?data:new Blob([data],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function pointRow(z=0,r=0){const tr=document.createElement('tr');tr.innerHTML='<td></td><td><input type="number" step="any" aria-label="頂点のz mm"></td><td><input type="number" step="any" aria-label="頂点の半径 mm"></td><td><button type="button">削除</button></td>';const ins=tr.querySelectorAll('input');ins[0].value=z;ins[1].value=r;tr.querySelector('button').onclick=()=>{tr.remove();renumber();geometryChanged();};$('points').tBodies[0].append(tr);renumber();}
function renumber(){[...$('points').tBodies[0].rows].forEach((row,i)=>row.cells[0].textContent=i);}
function arcRow(index=1,r=1,direction='ccw'){const tr=document.createElement('tr');tr.innerHTML='<td><input type="number" step="1" min="1" aria-label="円弧の終点番号"></td><td><input type="number" step="any" aria-label="円弧半径 mm"></td><td><select aria-label="円弧の方向"><option value="ccw">反時計回り</option><option value="cw">時計回り</option></select></td><td><button>削除</button></td>';const ins=tr.querySelectorAll('input');ins[0].value=index;ins[1].value=r;tr.querySelector('select').value=direction;tr.querySelector('button').onclick=()=>{tr.remove();geometryChanged();};$('arcs').tBodies[0].append(tr);}
function geometryChanged(){assemblyActive=false;markDirty();}
function showGeometry(){const kind=$('geometry-type').value;$('cylinder').hidden=kind!=='pillbox';$('profile-editor').hidden=kind==='pillbox';$('arc-editor').hidden=kind!=='arc_profile';}
function geometry(){const kind=$('geometry-type').value;if(kind==='pillbox')return {type:kind,radius_m:number('radius')/1000,length_m:number('length')/1000};
 const value=(input)=>{if(input.value.trim()===''||!Number.isFinite(Number(input.value)))throw Error('頂点・円弧の数値を確認してください');return Number(input.value);};
 const g={type:kind,points_zr_m:[...$('points').tBodies[0].rows].map(row=>[...row.querySelectorAll('input')].map(i=>value(i)/1000))};
 if(kind==='arc_profile'){g.chord_tolerance_m=number('chord')/1000;g.arcs=[...$('arcs').tBodies[0].rows].map(row=>{const ins=row.querySelectorAll('input');return {end_index:value(ins[0]),radius_m:value(ins[1])/1000,direction:row.querySelector('select').value};});}return g;}
function collect(){const mesh={nr:number('nr'),nz:number('nz'),triangulation:$('triangulation').value};for(const [id,key] of [['boundary-size','boundary_max_edge_m'],['corner-size','corner_max_edge_m'],['corner-radius','corner_radius_m']])if($(id).value!=='')mesh[key]=number(id)/1000;
 const p={project_version:1,case:{schema_version:2,name:$('name').value,geometry:geometry(),mesh,solver:{modes:number('modes')},rf:{beta:number('beta'),conductivity_s_per_m:number('conductivity'),normalization_j:number('energy')},boundaries:{z_min:$('z-min').value,z_max:$('z-max').value}},reflect_full:$('reflect').checked,display_length_unit:'mm'};
 if(assemblyActive)p.sections=structuredClone(sections);return p;}
function setGeometry(g){const pts=g.points_zr_m;const cylinder=g.type==='pillbox'||(g.type==='profile'&&pts?.length===2&&pts[0][1]===pts[1][1]);$('geometry-type').value=cylinder?'pillbox':g.type;
 $('points').tBodies[0].replaceChildren();$('arcs').tBodies[0].replaceChildren();
 if(cylinder){$('radius').value=(g.radius_m??pts[0][1])*1000;$('length').value=(g.length_m??pts[1][0])*1000;pointRow(0,number('radius'));pointRow(number('length'),number('radius'));}else for(const [z,r]of pts)pointRow(z*1000,r*1000);
 for(const a of g.arcs||[])arcRow(a.end_index,a.radius_m*1000,a.direction);$('chord').value=(g.chord_tolerance_m??.00001)*1000;showGeometry();}
function applyProject(p){const c=p.case;setGeometry(c.geometry);$('name').value=c.name;for(const [id,v]of Object.entries({nr:c.mesh.nr,nz:c.mesh.nz,modes:c.solver.modes,beta:c.rf.beta,conductivity:c.rf.conductivity_s_per_m,energy:c.rf.normalization_j}))$(id).value=v;
 $('z-min').value=c.boundaries?.z_min||'pec';$('z-max').value=c.boundaries?.z_max||'pec';$('reflect').checked=p.reflect_full;$('triangulation').value=c.mesh.triangulation||'diagonal';
 for(const [id,key]of [['boundary-size','boundary_max_edge_m'],['corner-size','corner_max_edge_m'],['corner-radius','corner_radius_m']])$(id).value=c.mesh[key]===undefined?'':c.mesh[key]*1000;
 sections=structuredClone(p.sections||[]);assemblyActive=sections.length>0;renderSections();dirty=false;$('dirty').textContent='入力を読込済み';}
function renderSections(){$('sections').replaceChildren();sections.forEach((s,i)=>{const div=document.createElement('div');div.className='job';const label=document.createElement('label');label.textContent=`部分 ${i+1} / ${s.geometry.type} — 繰り返し数`;const input=document.createElement('input');input.type='number';input.min=1;input.step=1;input.value=s.count;input.onchange=()=>{s.count=Number(input.value);assemblyActive=false;markDirty();};label.append(input);div.append(label);const edit=document.createElement('button');edit.textContent='輪郭へ読込';edit.onclick=()=>{setGeometry(s.geometry);assemblyActive=false;markDirty();};div.append(edit);const remove=document.createElement('button');remove.textContent='削除';remove.onclick=()=>{sections.splice(i,1);assemblyActive=false;renderSections();markDirty();};div.append(remove);$('sections').append(div);});}
function drawOutline(points){const svg=$('shape');svg.replaceChildren();const ns='http://www.w3.org/2000/svg';const L=points.at(-1)[0],R=Math.max(...points.map(p=>p[1])),scale=Math.min(700/L,210/R),x=z=>55+z*scale,y=r=>235-r*scale;
 const el=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);return e;};
 el('polygon',{points:[[0,0],...points,[L,0]].map(([z,r])=>`${x(z)},${y(r)}`).join(' '),fill:'#d7e9f8',stroke:'#1d6d9b','stroke-width':2});el('line',{x1:x(0),y1:y(0),x2:x(L),y2:y(0),stroke:'#526d84','stroke-dasharray':'5 4'});
 el('text',{x:55,y:263},'軸 r=0');el('text',{x:360,y:263},`z →  全長 ${(L*1000).toPrecision(6)} mm`);el('text',{x:55,y:18},`r ↑  最大半径 ${(R*1000).toPrecision(6)} mm`);$('shape-info').textContent=`${points.length} 輪郭点`;$('preview-note').textContent='入力形状（円弧は指定した弦誤差で表示）。側壁はPECです。';}
async function preview(){const r=await api('normalize',{document:collect()});drawOutline(r.outline_zr_m);return r.project;}
bind('preview',preview);
bind('new',async()=>{if(dirty&&!confirm('編集中の内容を保存せず新規作成しますか？'))return;const r=await api('normalize',{document:{schema_version:1,name:'新しい空洞',geometry:{type:'pillbox',radius_m:.06,length_m:.09}}});applyProject(r.project);drawOutline(r.outline_zr_m);});
$('open').onchange=async e=>{try{if(!e.target.files.length)return;const r=await api('normalize',{document:await e.target.files[0].text()});applyProject(r.project);drawOutline(r.outline_zr_m);$('error').hidden=true;}catch(err){failure(err);}finally{e.target.value='';}};
bind('save',async()=>{const p=await preview();download('cavity-project.json',JSON.stringify(p,null,2));dirty=false;$('dirty').textContent='保存用ファイルを出力';});
bind('export',async()=>download('case.json',JSON.stringify((await preview()).case,null,2)));
bind('add-point',()=>{const rows=$('points').tBodies[0].rows;const last=rows[rows.length-1]?.querySelectorAll('input');pointRow(last?Number(last[0].value)+10:0,last?Number(last[1].value):50);geometryChanged();});
bind('add-arc',()=>{arcRow();geometryChanged();});
$('geometry-type').onchange=()=>{showGeometry();geometryChanged();};
for(const id of ['points','arcs','radius','length','chord'])$(id).addEventListener('input',geometryChanged);
bind('append-section',async()=>{const r=await api('normalize',{document:{schema_version:2,geometry:geometry()}});sections.push({geometry:r.project.case.geometry,count:1});assemblyActive=false;renderSections();markDirty();});
bind('assemble',async()=>{const p=collect();const r=await api('assemble',{case:p.case,sections,reflect_full:p.reflect_full});applyProject(r.project);drawOutline(r.outline_zr_m);dirty=true;$('dirty').textContent='組立を展開済み — 未保存';});
bind('clear-sections',()=>{sections=[];assemblyActive=false;renderSections();markDirty();});
bind('run',async()=>{$('run').disabled=true;try{const p=await preview();await api('start',{document:p});await refreshJobs();}finally{$('run').disabled=false;}});
const statusNames={queued:'待機',running:'計算中',complete:'計算完了 / 数値検証は別途',failed:'失敗',cancelled:'中止',interrupted:'中断'};
async function refreshJobs(){const jobs=await api('jobs');$('jobs').replaceChildren();if(!jobs.length)$('jobs').textContent='計算はまだありません。';for(const j of jobs){const row=document.createElement('div');row.className='job';const title=document.createElement('strong');title.textContent=statusNames[j.status]||j.status;row.append(title);const desc=document.createElement('small');desc.textContent=`${j.id}${j.elapsed_seconds!==undefined?' / '+j.elapsed_seconds.toFixed(2)+'秒':''}${j.error?' / '+j.error:''}`;row.append(desc);
 const action=document.createElement('button');action.textContent=['running','queued'].includes(j.status)?'中止':'結果を開く';action.disabled=!['running','queued','complete'].includes(j.status);action.onclick=async()=>{try{if(['running','queued'].includes(j.status)){await api('cancel',{id:j.id});await refreshJobs();}else await openResult(j.id);}catch(e){failure(e);}};row.append(action);const log=document.createElement('button');log.textContent='ログ';log.onclick=async()=>{try{const r=await api('log',{id:j.id});$('error').hidden=false;$('error').textContent=r.text||'ログは空です。';}catch(e){failure(e);}};row.append(log);$('jobs').append(row);}}
bind('refresh',refreshJobs);
async function openResult(id){const r=await api('result',{id});currentResult=r;currentJob=id;$('result-controls').hidden=false;$('result-name').textContent=r.result.case.name;$('result-state').textContent='保存済みの結果を表示中。編集中の条件とは独立しています。メッシュ収束は未検証。';$('mode').replaceChildren();for(const q of r.result.modes){const opt=document.createElement('option');opt.value=q.mode_index;opt.textContent=`${q.mode_index} — ${(q.frequency_hz/1e6).toFixed(6)} MHz`;$('mode').append(opt);}$('probe-z').value=r.result.case.geometry.points_zr_m.at(-1)[0]*250;
 $('conventions').replaceChildren();for(const [key,value]of Object.entries(r.result.conventions)){const p=document.createElement('p');p.textContent=`${key}: ${value}`;$('conventions').append(p);}renderRF();await plot();}
const rfColumns=[['mode_index','番号'],['frequency_hz','周波数 [Hz]'],['q0','Q₀'],['r_over_q_accelerator_ohm','R/Q acc [Ω]'],['r_over_q_circuit_ohm','R/Q circuit [Ω]'],['stored_energy_j','U [J]'],['transit_time_factor_abs','TTF (abs)'],['epk_over_eacc_estimate','Epk/Eacc (推定)']];
function renderRF(){const table=document.createElement('table'),head=document.createElement('tr');for(const[,label]of rfColumns){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const q of currentResult.result.modes){const row=document.createElement('tr');for(const[key]of rfColumns){const td=document.createElement('td');td.textContent=q[key]===null?'未定義':Number(q[key]).toPrecision(7);row.append(td);}table.append(row);}$('rf-table').replaceChildren(table);}
async function plot(){$('plot').disabled=true;$('result-state').textContent='保存場を描画中…';try{const blob=await api('plot',{id:currentJob,mode:number('mode'),probe_z_m:number('probe-z')/1000,mesh:$('mesh-view').checked},true);if(imageURL)URL.revokeObjectURL(imageURL);imageURL=URL.createObjectURL(blob);$('field-image').src=imageURL;$('field-image').hidden=false;await $('field-image').decode();$('save-plot').disabled=false;$('result-state').textContent='保存されたFEM場。計算完了 / メッシュ収束は未検証。';}finally{$('plot').disabled=false;}}
bind('plot',plot);bind('restore',()=>{applyProject(currentResult.project);return preview();});
bind('csv',()=>{const rows=currentResult.result.modes,keys=Object.keys(rows[0]);download('modes.csv',[keys.join(','),...rows.map(q=>keys.map(k=>q[k]??'').join(','))].join('\n'),'text/csv');});
bind('save-plot',async()=>download('fields.png',await(await fetch(imageURL)).blob(),'image/png'));
document.querySelector('.editor').addEventListener('input',markDirty);
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
pointRow(0,60);pointRow(90,60);showGeometry();
if(!token)failure(Error('起動時に表示されたURLから開いてください。'));
else{preview().catch(failure);refreshJobs().catch(failure);setInterval(()=>refreshJobs().catch(()=>{}),2500);}
